imports:
  - { resource: parameters.yml }
  - { resource: security.yml }

framework:
  secret: "%secret%"
  session: ~
  templating:
    engines: ['twig']
  assets: ~
  profiler:
    collect: false
  lock:
    resources:
      satis: "flock"
      build: "flock"

twig:
  form_themes: ['bootstrap_3_layout.html.twig']

jms_serializer:
  visitors:
    json:
      options:
        - JSON_PRETTY_PRINT
        - JSON_UNESCAPED_SLASHES
        - JSON_UNESCAPED_UNICODE
