parameters:
    secret: "ThisTokenIsNotSoSecretChangeIt"
    satis_filename: "%kernel.project_dir%/satis.json"
    satis_log_path: "%kernel.project_dir%/var/satis"
    admin.auth: true
    admin.users:
        microweber_private:
            password: 'f3f87wfcgyw34hfchu'
            roles: 'ROLE_ADMIN'
    composer.home: "%kernel.project_dir%/var/composer"
    github.secret: ~
    gitlab.secret: ~
    gitlab.auto_add_repo: false
    gitlab.auto_add_repo_type: ~